# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [3]:
np.__version__
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/izabe/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/izabe/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/izabe/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/U

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [8]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [12]:
vector.size

10

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [39]:
python -c "import numpy; numpy.info(numpy.add)"


SyntaxError: invalid syntax (<ipython-input-39-edce3148ed5b>, line 3)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [13]:
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [27]:
x = np.arange(10,50) 
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [28]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [29]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [33]:
x = np.array([1,2,0,0,4,0])
x
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [34]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [36]:
arr = np.random.random((3,3,3))
print(arr)

[[[0.69026749 0.48087174 0.47785002]
  [0.8922237  0.39444215 0.47422696]
  [0.93526023 0.21287707 0.7153308 ]]

 [[0.46351318 0.87726739 0.02551544]
  [0.78122809 0.71312129 0.68896511]
  [0.44014317 0.85328004 0.48496697]]

 [[0.23098165 0.92180499 0.55732379]
  [0.1410725  0.31349736 0.75086539]
  [0.19458348 0.58224235 0.55678597]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [45]:
arr1 = np.random.random((10,10))
arr1.min() , arr1.max()

(0.0060005921587332756, 0.9923090113743199)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [9]:
arr2 = np.random.random(30)
arr2.mean()

0.4755154062664461

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [13]:
arr3 = np.ones((10,10))
arr3[1:-1, 1:-1] = 0
print(arr3)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [44]:
arr6 = np.ones((10,10))
arr6 = np.pad(arr6, pad_width=1, mode='constant', constant_values=0)
print(arr6)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [45]:
NaN

False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [26]:
a = np.zeros((5, 5), int)
np.fill_diagonal(a, np.arange(5))

print(a)


[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [10]:
import numpy as np
arr = np.ones((8,8), dtype=int)
arr[::2, 1::2] = 0
arr[1::2, ::2] = 0
print(arr)





[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [85]:
#nie rozumiem funkcji 
arr = np.unravel_index(100,(6,7,8))
print(arr)


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [89]:
b = np.array([[0,1], [1,0]])
np.tile(b, (4,4))



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - mean) / std)

In [17]:
arr4 = np.random.random((5,5))
arr4_max= arr4.max()
arr4_min= arr4.min()
std = (arr4 - arr4_min)/(arr4_max-arr4_min)
print(std)


[[0.98692223 0.61033627 0.40085904 0.93914868 0.36386752]
 [0.88265074 0.92723481 0.61057819 0.52013657 0.        ]
 [0.5971838  0.68178438 0.82280999 0.10823576 1.        ]
 [0.11773154 0.06046733 0.88593198 0.46186133 0.03202395]
 [0.56418509 0.15093218 0.86042576 0.83400061 0.56532445]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [84]:
matrix = np.dot(np.ones((5,3)), np.ones((3,2)) )
print(matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [23]:
arr5 = np.arange(10)
arr5[(arr5 >= 3) & (arr5 <= 8) ] *= -1
print(arr5)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [29]:
10
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [61]:
z = np.ones(5)
print(z**z)
# print(2 << z <<2) error  
print(z <- z)
print(1j*z)
print(z/1/1)
# print(z<z>z) error 

[1. 1. 1. 1. 1.]
[False False False False False]
[0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
[1. 1. 1. 1. 1.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [19]:
ZeroDivisionError

ZeroDivisionError: division by zero

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [78]:
arr = np.random.uniform(-10,10,10)
print(arr)
print(np.trunc(arr + np.copysign(0.5,arr)))



[ 0.63553998  7.05758897  9.6704781   5.20926783 -0.30299798  8.99654634
  4.5176111  -4.54173772  2.08932157  5.23161227]
[ 1.  7. 10.  5. -0.  9.  5. -5.  2.  5.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [31]:
a = np.ones(4)
print(a)
b = np.arange(10)
print(b)
c = np.intersect1d(a,b)
print(c)

[1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]
[1.]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [18]:
war = np.seterr(all='ignore')
np.arange(3) / 0

with np.errstate(divide='warn'):
    np.arange(3) / 0

C:\Users\izabe\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [31]:
False 

C:\Users\izabe\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [38]:
import datetime
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1)
print(yesterday,today,tomorrow)

2019-02-11 2019-02-12 2019-02-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [48]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [52]:
A = np.random.random_sample((1,4))

B = np.random.random_sample((1, 4))

np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A,out=A)
np.multiply(A,B, out=A)








[[0.32196743 0.02665942 0.62739128 0.73979156]]
[[0.64047413 0.07915269 0.14703666 0.50985742]]


array([[-0.15493742, -0.00141045, -0.24293467, -0.46223988]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [14]:
arr = np.random.uniform(-10,10,10)
print(arr)
print(arr - arr%1)
print(np.ceil(arr))
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))


[ 9.74880889 -2.3360212   3.90726897  0.54822814  6.90046513  8.99084513
 -2.77872404 -9.80763109 -3.47564389  6.97993166]
[  9.  -3.   3.   0.   6.   8.  -3. -10.  -4.   6.]
[10. -2.  4.  1.  7.  9. -2. -9. -3.  7.]
[  9.  -3.   3.   0.   6.   8.  -3. -10.  -4.   6.]
[ 9 -2  3  0  6  8 -2 -9 -3  6]
[ 9. -2.  3.  0.  6.  8. -2. -9. -3.  6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [50]:
arr7 = np.zeros((5,5))
arr7 += np.arange(5)
print(arr7)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [36]:

def gen():
    for i in range(10):
        yield i
        
arr = np.fromiter(gen(),dtype=int)
print(arr)

        


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [22]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [53]:
arr = np.random.random(10)
arr.sort()
print(arr)

[0.05204654 0.11827189 0.2499273  0.41879126 0.47557791 0.56544582
 0.70272396 0.79382702 0.91489135 0.95303131]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [14]:
s = np.arange(10).reshape(2,5)
np.add.reduce(s)

array([ 5,  7,  9, 11, 13])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [83]:

A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
are_equal = np.allclose(A,B)
print(are_equal)
print(A)
print(B)

False
[8 9 1 6 9 1 6 1 9 8]
[3 1 1 0 8 4 2 7 2 7]


#### 43. Make an array immutable (read-only) (★★☆) (**hint**: flags.writeable)

In [6]:
array_im = np.ones(10)
array_im.flags.writeable = False 





#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [34]:
a = np.random.random((10,2))
#print(a)
x = a[:,0]
y = a[:,1]
z = np.sqrt(x**2+y**2)
matrix = np.arctan2(x,y)
print(z)
print(matrix)


[0.56053669 0.80707915 1.04588741 0.19755975 0.51773384 0.68282603
 0.58692893 0.97712912 0.88124128 0.65649415]
[1.23232278e+00 5.54174652e-01 6.50599728e-01 1.09572675e+00
 5.16698133e-01 1.11119584e+00 5.93931772e-01 1.74506436e-01
 7.29926327e-01 1.21399152e-03]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [16]:
vector = np.random.random(10)
vector[vector.argmax()]= 0 
print(vector)

[0.78858898 0.41922958 0.4788013  0.85784905 0.42514657 0.50034991
 0.         0.50767147 0.70242156 0.44782781]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [9]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [1]:

np.set_printoptions()
arr = np.ones((10,10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [46]:
a = np.arange(10).reshape(2,5)
print(np.argmin(a))


0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

[((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1)) ((1, 1), (1, 1, 1))
 ((1, 1), (1, 1, 1))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
a = np.arange(10, dtype=np.int32)
a = a.astype(np.float32, copy=False)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [30]:
a = np.array([[1, 2, 5], [3, 4, 1]])
for index, x in np.ndenumerate(a):
    print(index, x)
    
    
for index in np.ndindex(3, 2, 1):
    print(index)


(0, 0) 1
(0, 1) 2
(0, 2) 5
(1, 0) 3
(1, 1) 4
(1, 2) 1
(0, 0, 0)
(0, 1, 0)
(1, 0, 0)
(1, 1, 0)
(2, 0, 0)
(2, 1, 0)


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [70]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x**2+y**2)
sigma, m = 1.0, 0.0
result = np.exp(-( (d-m)**2 / ( 2.0 * sigma**2 ) ) )
print(result)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [75]:
p = 4
arr = np.ones((10,10))
np.put(arr, np.random.choice(range(10), p, replace=False),1)




#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [74]:
matrix = np.random.rand(4,5)
result = matrix - matrix.mean(axis=1, keepdims=1)
print(matrix)
print(result)


[[5.09668044e-01 3.77675978e-02 9.78261112e-01 3.09763220e-01
  9.03961096e-01]
 [9.29276479e-01 1.08187724e-01 6.32903788e-01 4.30555885e-01
  3.87834252e-02]
 [2.70625918e-01 8.60672719e-04 6.63169862e-01 9.64012911e-01
  7.83297130e-01]
 [6.50097885e-01 7.81918578e-01 3.36185344e-01 7.69064478e-02
  3.07095935e-01]]
[[-0.03821617 -0.51011662  0.4303769  -0.23812099  0.35607688]
 [ 0.50133502 -0.31975374  0.20496233  0.00261442 -0.38915804]
 [-0.26576738 -0.53553263  0.12677656  0.42761961  0.24690383]
 [ 0.21965705  0.35147774 -0.09425549 -0.35353439 -0.1233449 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [79]:
x = np.random.rand(4,5)
print(x)
print(x[x[:,0].argsort()])


[[0.56712258 0.06381009 0.73537002 0.58003146 0.63488831]
 [0.47779624 0.02307961 0.74727354 0.54647098 0.03405306]
 [0.61157108 0.82676321 0.96631726 0.02842733 0.41578262]
 [0.10581072 0.46345845 0.89825785 0.94606689 0.43124767]]
[[0.10581072 0.46345845 0.89825785 0.94606689 0.43124767]
 [0.47779624 0.02307961 0.74727354 0.54647098 0.03405306]
 [0.56712258 0.06381009 0.73537002 0.58003146 0.63488831]
 [0.61157108 0.82676321 0.96631726 0.02842733 0.41578262]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [65]:

arr1 = np.array([[1, 2, 5], [3, 4,np.NaN]])
print((~arr1.any(axis=1)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [68]:
a = np.random.random(10)
nearest = 1
result = a.flat[np.abs(a - nearest).argmin()]
print(result)


0.8789026663155645


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [94]:
a = np.random.rand(1,3)
b = np.random.rand(3,1)
#print(a)
#print(b)
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])
          

[[0.33150032 0.82837888 0.13569263]
 [1.26078638 1.75766494 1.06497869]
 [0.35665572 0.85353428 0.16084803]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [62]:
a = np.arange(5)
print(a)
print(np.bincount(a))

[0 1 2 3 4]
[1 1 1 1 1]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [66]:
F = np.ones(10)
X = np.arange(10)
F+= np.bincount(X)
print(F)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [76]:
x = np.random.rand(4, 3, 3, 2)
x.sum(axis=(-2,-1))


array([[4.10546251, 4.0518753 , 2.00877463],
       [4.33507308, 3.8272184 , 2.2871858 ],
       [3.11354524, 2.2292348 , 3.15953249],
       [3.75705034, 2.08129498, 3.13801268]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [14]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
print(a)
print(b)
print(np.dot(a,b))
print(np.diag(np.dot(a, b)))



[[1, 0], [0, 1]]
[[4, 1], [2, 2]]
[[4 1]
 [2 2]]
[4 2]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)