Find 5 csv file with huge amount of data on internet and create NumPy array of them (see appendix 9)

In [65]:
import numpy as np
import pandas as pd
import csv

df1 = pd.read_csv('cscpopendata.csv')
print(df1)

df2 = pd.read_csv('NCHS_-_Death_rates_and_life_expectancy_at_birth.csv')
print(df2)

df3 = pd.read_csv('NCHS_-_Leading_Causes_of_Death__United_States.csv')
print(df3)

df4 = pd.read_csv('Nutrition__Physical_Activity__and_Obesity_-_Women__Infant__and_Child.csv')
print(df4)

df5 = pd.read_csv('SSA-SA-FYWL.csv')
print(df5)


import csv

cscpopendata = []

with open('cscpopendata.csv', newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        cscpopendata.append(row)
        
cscpopendata

import csv

death_rates = []

with open('NCHS_-_Death_rates_and_life_expectancy_at_birth.csv', newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        death_rates.append(row)
        
death_rates

import csv

leading_causes = []

with open('NCHS_-_Leading_Causes_of_Death__United_States.csv', newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        leading_causes.append(row)
        
leading_causes


import csv

nutrition_act_obes = []

with open('Nutrition__Physical_Activity__and_Obesity_-_Women__Infant__and_Child.csv', newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        nutrition_act_obes.append(row)
        
nutrition_act_obes


import csv

ssa = []

with open('SSA-SA-FYWL.csv', newline='') as File:
    reader = csv.reader(File)
    for row in reader:
        ssa.append(row)
        
ssa



[['File Name',
  'File Version',
  'Update Date',
  'Region Code',
  'State Code',
  'Date Type',
  'Date',
  'Population age 18-64',
  'SSA Disabilty Beneficiaries  age 18-64',
  'Percent of Adult Population Receiving SSA Adult Disability Benefits',
  'Eligible Adult Population',
  'Adult Receipts',
  'Eligible Adult Population Filing Rate',
  'Favorable Adult Determinations',
  'Eligible Adult Population Allowance Rate',
  'All Adult Determinations',
  'Adult Favorable  Determination Rate',
  'Population under age 18',
  'SSI Disabled Child (DC) Beneficiaries',
  'Percent of Population under age 18 Receiving SSI DC Benefits',
  'Eligible Child Population',
  'SSI Disabled Child (DC) Receipts',
  'Eligible Child Population Filing Rate',
  'Favorable SSI Child (DC) Determinations',
  'Eligible Child Population Allowance Rate',
  'All SSI Disabled Child Determinations',
  'SSI Disabled Child Allowance Rate',
  'All Determinations',
  'All Favorable Determinations',
  'Favorable Determin

Print axes of each array

In [75]:
pd.concat([df1, df2, df3, df4, df5], join='inner')
pd.concat([df1, df2, df3, df4, df5], join='inner', axis=1)


CDPHId                                        ProductName  CSFId  \
0         2   ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES    NaN   
1         3                         Glover's Medicated Shampoo    NaN   
2         3                         Glover's Medicated Shampoo    NaN   
3         4           PRECISION GLIMMER EYE LINER-ALL SHADES �    NaN   
4         5        AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �    NaN   
5         6  JILLIAN DEMPSEY FOR AVON CELESTIAL EYESHADOW-A...    NaN   
6         7  ABSOLUTE Precision Color Powder System - All S...  310.0   
7         7  ABSOLUTE Precision Color Powder System - All S...  311.0   
8         7  ABSOLUTE Precision Color Powder System - All S...  312.0   
9         8  ABSOLUTE Precision Color Powder System Opaque ...  313.0   
10        9  ABSOLUTE Precesion Color Powder System Perfect...    NaN   
11       10  ABSOLUTE Precision Color Powder System Translu...  314.0   
12       12    ABSOLUTE FX Chromatones Precision Color Powders  315.0   
13       12    ABSOLUTE FX Chromatones Precision Color Powders  316.0   
14       13                                             BlueFX  317.0   
15       13                                             BlueFX  318.0   
16       13                                             BlueFX  319.0   
17       14                                            GreenFX  320.0   
18       14                                            GreenFX  321.0   
19       14                                            GreenFX  322.0   
20       14                                            GreenFX  323.0   
21       15                          I'm not Really a Waitress  324.0   
22       15                          I'm not Really a Waitress  325.0   
23       15                          I'm not Really a Waitress  326.0   
24       15                          I'm not Really a Waitress  327.0   
25       16                                        Kyoto Pearl  328.0   
26       16                                        Kyoto Pearl  329.0   
27       17                                      Radiant RedFX  330.0   
28       17                                      Radiant RedFX  331.0   
29       17                                      Radiant RedFX  332.0   
..      ...                                                ...    ...   
750     481                           LiPigments Aqua Pigments   51.0   
751     481                           LiPigments Aqua Pigments   52.0   
752     481                           LiPigments Aqua Pigments   53.0   
753     481                           LiPigments Aqua Pigments   54.0   
754     481                           LiPigments Aqua Pigments   55.0   
755     481                           LiPigments Aqua Pigments   56.0   
756     481                           LiPigments Aqua Pigments   57.0   
757     481                           LiPigments Aqua Pigments   58.0   
758     481                           LiPigments Aqua Pigments   59.0   
759     481                           LiPigments Aqua Pigments   60.0   
760     481                           LiPigments Aqua Pigments   61.0   
761     481                           LiPigments Aqua Pigments   62.0   
762     481                           LiPigments Aqua Pigments   63.0   
763     481                           LiPigments Aqua Pigments   64.0   
764     482                          Mei-Cha Elegance Pigments  219.0   
765     482                          Mei-Cha Elegance Pigments  220.0   
766     482                          Mei-Cha Elegance Pigments  221.0   
767     482                          Mei-Cha Elegance Pigments  222.0   
768     482                          Mei-Cha Elegance Pigments  223.0   
769     482                          Mei-Cha Elegance Pigments  224.0   
770     482                          Mei-Cha Elegance Pigments  225.0   
771     482                          Mei-Cha Elegance Pigments  226.0   
772     482                          Mei-Cha Elegance Pigments 

Create NumPy array of each file with: size, shape and data type. Print out.

In [66]:
df1.info()
df1.shape
df1.size

df2.info()
df2.shape
df2.size

df3.info()
df3.shape
df3.size

df4.info()
df4.shape
df4.size

df5.info()
df5.shape
df5.size

df2.info()
df2.shape
df2.size

AttributeError: 'list' object has no attribute 'info'

If is it possible remove all data without integers/floats and then print type of array

In [31]:
import pandas as pd
df1 = pd.read_csv('cscpopendata.csv')
to_drop = ['ProductName','CSF','CompanyName','BrandName']
df1.drop(to_drop, inplace=True, axis=1)
#print(df1)
df1.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96896 entries, 0 to 96895
Data columns (total 18 columns):
CDPHId                    96896 non-null int64
CSFId                     68300 non-null float64
CompanyId                 96896 non-null int64
PrimaryCategoryId         96896 non-null int64
PrimaryCategory           96896 non-null object
SubCategoryId             96896 non-null int64
SubCategory               96896 non-null object
CasId                     96896 non-null int64
CasNumber                 92312 non-null object
ChemicalId                96896 non-null int64
ChemicalName              96896 non-null object
InitialDateReported       96896 non-null object
MostRecentDateReported    96896 non-null object
DiscontinuedDate          12283 non-null object
ChemicalCreatedAt         96896 non-null object
ChemicalUpdatedAt         96896 non-null object
ChemicalDateRemoved       2723 non-null object
ChemicalCount             96896 non-null int64
dtypes: float64(1), int64(7), obje

Create new NumPy array using function and add markdown description to each one:
1. array,
2. zeros,
3. zeros_like,
4. ones,
5. ones_like,
6. empty,
7. empty_like,
8. arange,
9. linspace,
10. numpy.random.rand,
11. numpy.random.randn,
12. fromfunction,
13. fromfile

#### Array - create an array , parameters -> np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)¶

In [54]:
x = np.array([[2,3,1,0], [1,4,6,7], [10,5,3,4]])
print(x)

[[ 2  3  1  0]
 [ 1  4  6  7]
 [10  5  3  4]]


#### Zeros - return a new array of given shape and type , filled with zeros , parameters -> n[.zeros(shape, dtype=float, order='C')

In [52]:
arr = np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Zeros_like - return an array of zeros with the same shape and type as a given array. parameters -> np.zeros_like(a, dtype=None, order='K', subok=True


In [56]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### Ones - return a new array of given shape and type, filled with ones. parameters -> numpy.ones(shape, dtype=None, order='C')


In [57]:
arr2 = np.ones((4,8))
print(arr2)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### Ones_like - return an array of ones with the same shape and type as a given array. parameters -> np.ones_like(a, dtype=None, order='K', subok=True)


In [59]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### Empty - return a new array of given shape and type, without initializing entries. parameters -> np.empty(shape, dtype=float, order='C')



In [7]:
a = np.empty([2, 4], dtype=int)
print(a)

[[-433028288        429 1833498752          0]
 [         2          0         -1         -1]]


#### Empty_like - return a new array with the same shape and type as a given array. parameters -> np.empty_like(prototype, dtype=None, order='K', subok=True)

In [8]:
np.empty_like(a)

array([[-466123856,        429, 1833498752,          0],
       [         3,          0,         -1,         -1]])

#### Arange - return evenly spaced values within a given interval. parameters -> np.arange([start, ]stop, [step, ]dtype=None)

In [10]:
np.arange(6,16,2)

array([ 6,  8, 10, 12, 14])

#### Linspace - return evenly spaced numbers over a specified interval. Returns num evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be excluded. parameters ->  np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [14]:
np.linspace(2.0, 3.0, num=10, endpoint=False)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

#### Numpy.random.rand - create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1). parameters -> np.random.rand(d0, d1, ..., dn)

In [17]:
np.random.rand(2,3)

array([[0.09500747, 0.58883708, 0.35585267],
       [0.59302508, 0.91101157, 0.96443386]])

#### Numpy.random.randn - return a sample (or samples) from the “standard normal” distribution. parameters -> np.random.randn(d0, d1, ..., dn)

In [18]:
np.random.randn(2, 4) 

array([[ 0.81132121, -1.69558907, -1.20507938, -3.29238474],
       [ 1.82882252,  0.28096808,  1.23927162,  1.58759183]])

#### Fromfunction - construct an array by executing a function over each coordinate. The resulting array therefore has a value fn(x, y, z) at coordinate (x, y, z). paramters 0> np.fromfunction(function, shape, **kwargs)

In [22]:
np.fromfunction(lambda i, j : i + j , (4, 4), dtype=int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

#### Fromfile - construct an array from data in a text or binary file. parameters -> np.fromfile(file, dtype=float, count=-1, sep='')

In [29]:
import numpy as np
import os

f = open("cscpopendata.csv", "rb")
data = np.fromfile(f)
print(data) 

[1.64376963e+078 5.35206296e+160 1.25024073e+175 ... 8.06988175e-144
 2.92390761e-081 2.91061194e-144]
